### ISSUE TITLE
"AHC" from library

### ISSUE THREAD

**Issue by cherif54** [BUTSpeechFIT/VBx#42]
"AHC" is missing from diarization_lib.py and its called a couple of times in vbhmm.py. 
![Screenshot from 2022-05-06 19-51-03](https://user-images.githubusercontent.com/77592579/167228824-f3ff3c33-f98b-4ee9-b311-34b621eaea01.png)

**Comment by fnlandini** [comment]
Hi, sorry for that. I made an update recently that cleaned up the notation and forgot to add the clustering based on scipy instead of calling our own defined AHC. It should be fixed now. Please, let me know if you find any trouble.

**Comment by ajcassell** [comment]
@fnlandini  I pulled the most recent code and I am still seeing this issue. When I try to run ./run_example.sh on my own data, vbhmm.py is not running because 

`Traceback (most recent call last):
  File "/.../VBx/vbhmm.py", line 42, in <module>
    from diarization_lib import read_xvector_timing_dict, l2_norm, \
ImportError: cannot import name 'AHC' from 'diarization_lib' (/.../VBx/diarization_lib.py)`

EDITED: Actually it appears I just needed to remove the AHC import.

**Comment by fnlandini** [comment]
Thank you for pointing it out and sorry I did not check that. I have just pushed the change. Please, let me know if you find any other trouble and thanks a lot.
